# Generated by Django 5.1.7 on 2025-04-01 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('departamento', models.CharField(choices=[('IT', 'Tecnología'), ('HR', 'Recursos Humanos'), ('FIN', 'Finanzas'), ('MKT', 'Marketing'), ('OPS', 'Operaciones')], max_length=50)),
                ('fecha_solicitud', models.DateField()),
                ('cargo', models.CharField(choices=[('analista', 'Analista'), ('jefe', 'Jefe de Departamento'), ('gerente', 'Gerente'), ('director', 'Director')], max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('finalidad', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisition.requisition')),
            ],
        ),
    ]
