# Generated by Django 5.1.7 on 2025-03-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='name',
            field=models.CharField(default='DEFAULT_NAME', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
